### ISSUE TITLE
Attempt to run, hit Syntax Error

### ISSUE THREAD

**Issue by beet-enjoyer** [cebtenzzre/tumblr-utils#16]
Using MacOSX Catalina 10.15.5 and Python 3.12.1. Downloaded tumblr-utils-master on Dec 11, 2023.
Command and error output:

> [username]@ca-7b7m2g2 tumblr-utils-master % python tumblr_backup.py -i --tag-index --save-video [blogname]
>      File "tumblr.backup.py", line 45
>         class Literal(metaclass=FakeGenericMeta):
>                                              ^
> Syntax Error: invalid syntax

that carrot points to the =
<p>
<img width="601" alt="tumblr-utils syntax error" src="https://github.com/cebtenzzre/tumblr-utils/assets/156368612/5801fd69-3547-4d25-8a44-cd63a0e6f8d6">
<p>
I know nothing about python and am following these tutorials: <p>
https://github.com/Cebtenzzre/tumblr-utils/blob/cebtenzzre/tumblr_backup_for_beginners.md <p>
https://docs.google.com/document/d/1yBWlk-yEgpSoEh3c9oLhz_kbLtUGqbqzOpCtJsvQgjI/edit#heading=h.z8o3nt60g1z2 <p>
(both are for windows, i'm making educated guesses about what to do for mac and am surprised I got this far) <p>
So I poke around in the script (a duplicate version so I don't fuck up the original) in IDLE and start deleting =signs and repeat the command in Terminal just to see what happens. It gets a few lines farther before it hits another syntax error. Many repetitions, similar results. It's usually unhappy about = or ==.

**Comment by cebtenzzre** [comment]
Please make sure you are *actually* using Python 3 (try using `python3` instead of `python`). The system Python provided by older versions of macOS is Python 2, which is very old (originally released in 2010) and we no longer provide support for it.
