### ISSUE TITLE
unexpected indent

### ISSUE THREAD

**Issue by mojii100** [cebtenzzre/tumblr-utils#17]
trying to run script gives unexpected indent error on line 2355. what is the expected indent?

commit: 563d6f1
python3 tumblr_backup.py -i --tag-index --save-video <blog>

error:
  File "/home/<user>/Downloads/tumblr-utils-master/tumblr_backup.py", line 2355
    wget_retrieve = WgetRetrieveWrapper(options, logger.log)
IndentationError: unexpected indent

**Comment by cebtenzzre** [comment]
Not sure what's going on there. If you `pip install tumblr-backup`, can you just `tumblr-backup ...`? It should be easier.

Otherwise, it would be good to know the output of `python3 --version` and `md5sum tumblr_backup.py`.

**Comment by mojii100** [comment]
I'm pretty sure I did, but I don't know what the correct indentation is and redownloading the file to reset the spacing still returns unexpected indent. how much whitespace exactly is supposed to be before that line? also running 'tumblr-backup <blog>' returns 'command not found'

**Comment by cebtenzzre** [comment]
Assuming you are not using a venv, it sounds like you need to add ~/.local/bin to your PATH. If you use bash, add this line to the end of your ~/.bashrc:
```bash
export PATH=~/.local/bin:$PATH
```
