### ISSUE TITLE
Download hidden tumblr

### ISSUE THREAD

**Issue by Letstrytumblr** [Cebtenzzre/tumblr-utils#3]
Hi, 
sorry to disturb you. I've managed to use the tumbrl-utils to download normal blogs, and it works without any problems. Your backup.py works very well as well.
But I just can't understand how you can use login.py and the other files to download hidden blogs. I've tried to copy the files in the same folder of backup.py, but it doesn't work (the folder with the blog name is created, but there isn't anything inside).
May you explain me how it can be done? Sorry, i'm just a newbie.
Thank you for your attention.

**Comment by Cebtenzzre** [comment]
Thanks for trying my fork!

First of all, I'm not sure which files you're copying, but you should download the whole repo [as a ZIP](https://github.com/Cebtenzzre/tumblr-utils/archive/svc.zip) if you haven't already, so you get all the necessary components. As for any other files, these scripts aren't picky where they are as long as you specify their paths correctly on the command line.

Sorry about the lack of documentation, I should get around to writing a little guide eventually. The gist is this:
1) You have two options for getting cookies, pick one:
 A) Run `python tumblr_login.py /path/to/cookies.txt`, where `/path/to/cookies.txt` is where you want the cookie file saved, including the filename. The script asks a few questions, logs into Tumblr, and dumps the cookies for you. OR,
 B) Get a browser extension such as [Get cookies.txt](https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid) (for Chrome - I use [this one](https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg) but it's missing) or [cookies.txt](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/) (for Firefox). Log into Tumblr if you're not already, and while Tumblr is open use the extension to save a `cookies.txt` somewhere.
2) Once you have a `cookies.txt` from either of the methods, you can use the `--cookiefile` option to tell `tumblr_backup.py` where it is, like this: `python tumblr_backup.py --cookiefile /path/to/cookies.txt blog_name`, where `/path/to/cookies.txt` is where the cookie file was saved.

The script automatically uses the svc API with cookies for dashboard-only blogs. If it still doesn't work, please provide the full command and the output of the script (blog name isn't necessary). BTW, if your cookies stop working after a while (weeks to months, or after logging out), they may have expired - you can delete the file and repeat the steps to get a fresh `cookies.txt`.

**Comment by Letstrytumblr** [comment]
Thank you for your patience!
I've tried to use your method and I've downloaded cookies.txt.
I've tried with a normal blog, it works.
But it still can't download hidden blogs.
I paste the results:

macbook-air-of-XX:~ XX$ python tumblr_backup.py --cookiefile /Users/XX/Downloads/cookies.txt blog name
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/blog name.tumblr.com/posts?reblog_info=true&api_key=DrosfHjSjg2LdOx4Y23XpM9HtjzSdPR26LnoHDPFbRRqiJ9nl6&limit=1
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/blog name.tumblr.com/posts?reblog_info=true&api_key=DrosfHjSjg2LdOx4Y23XpM9HtjzSdPR26LnoHDPFbRRqiJ9nl6&limit=1
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/blog name.tumblr.com/posts?reblog_info=true&api_key=DrosfHjSjg2LdOx4Y23XpM9HtjzSdPR26LnoHDPFbRRqiJ9nl6&limit=1
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/blog name.tumblr.com/posts?reblog_info=true&api_key=DrosfHjSjg2LdOx4Y23XpM9HtjzSdPR26LnoHDPFbRRqiJ9nl6&limit=1
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/blog name.tumblr.com/posts?reblog_info=true&api_key=DrosfHjSjg2LdOx4Y23XpM9HtjzSdPR26LnoHDPFbRRqiJ9nl6&limit=1
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/blog name.tumblr.com/posts?reblog_info=true&api_key=DrosfHjSjg2LdOx4Y23XpM9HtjzSdPR26LnoHDPFbRRqiJ9nl6&limit=1
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/blog name.tumblr.com/posts?reblog_info=true&api_key=DrosfHjSjg2LdOx4Y23XpM9HtjzSdPR26LnoHDPFbRRqiJ9nl6&limit=1
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/blog name.com/posts?reblog_info=true&api_key=DrosfHjSjg2LdOx4Y23XpM9HtjzSdPR26LnoHDPFbRRqiJ9nl6&limit=1
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/blog name.com/posts?reblog_info=true&api_key=DrosfHjSjg2LdOx4Y23XpM9HtjzSdPR26LnoHDPFbRRqiJ9nl6&limit=1
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/blog name.tumblr.com/posts?reblog_info=true&api_key=DrosfHjSjg2LdOx4Y23XpM9HtjzSdPR26LnoHDPFbRRqiJ9nl6&limit=1

Thank you for your help!

**Comment by Cebtenzzre** [comment]
That looks like the output of either bbolli's version of the script, or the wrong branch of my fork. The svc (default) branch of my fork would say something like `Error retrieving API repsonse` or `API response has non-200 status`. Make sure you are using the tumblr_backup.py found in _this_ repo.

**Comment by Cebtenzzre** [comment]
Closing as invalid. @Letstrytumblr Feel free to reopen if you still think there's a problem with this fork's tumblr_backup.py, but AFAIK you haven't actually ran my version yet.
