### ISSUE TITLE
Unable to download liked posts despite them being public

### ISSUE THREAD

**Issue by jessienab** [cebtenzzre/tumblr-utils#33]
So not sure what changed, but I'm unable to backup likes anymore. My last attempt seems to have been Feb 2024 using an older commit (can't recall sorry).

- The version (commit hash) of tumblr-utils you are using.

```
commit 27b6c448b94eb6a9fce5dcb6495ac82e11c0fc28 (HEAD -> cebtenzzre, origin/cebtenzzre, origin/HEAD)
Author: Cebtenzzre <cebtenzzre@gmail.com>
Date:   Fri Jul 28 22:49:26 2023 -0400
```

and
```
$ pip list install
Package            Version
------------------ ----------
beautifulsoup4     4.12.3
bs4                0.0.2
certifi            2024.8.30
charset-normalizer 3.4.0
ffmpeg             1.4
filetype           1.2.0
idna               3.10
lxml               5.3.0
pip                24.3.1
platformdirs       4.3.6
requests           2.32.3
soupsieve          2.6
**tumblr-backup      1.0.3**
urllib3            2.2.3
yt-dlp             2024.11.18
```

----

- The exact command you ran (excluding blog names if you prefer)

```
python tumblr-utils-cebtenzzre/tumblr_backup.py --json --save-video --save-audio --likes $BLOG
```

and

```
tumblr-backup --internet-archive --save-video --save-audio --likes
```

----

- Any relevant console output from tumblr-utils.

See this log for the .py output: [error_python.pyfile.log](https://github.com/user-attachments/files/17995194/error_python.pyfile.log)

See this log for the pip package output: [error_python.pip_package.log](https://github.com/user-attachments/files/17995199/error_python.pip_package.log)

----

- For crashes, a backtrace (if available).

See above logs

----

- For post-specific issues: Either an example post (blog + ID, or url), or the relevant JSON from that post (use -j)

I have 4 jsons saved from running the command with the .py file, here they are:

[767882704114089984.json](https://github.com/user-attachments/files/17995210/767882704114089984.json)
[768470743363289088.json](https://github.com/user-attachments/files/17995211/768470743363289088.json)
[768511193144049664.json](https://github.com/user-attachments/files/17995212/768511193144049664.json)
[768747584362872832.json](https://github.com/user-attachments/files/17995213/768747584362872832.json)

Though realistically this seems to be failing on *any* post so... :woman_shrugging: 

----

Saving normal reblogs and posts works fine without issue, using the pip tumblr-backup package.

Thank you!

**Comment by cebtenzzre** [comment]
This appears to be a duplicate of #27.
