### ISSUE TITLE
Unable to run even with API Key

### ISSUE THREAD

**Issue by Sheepykin** [Cebtenzzre/tumblr-utils#4]
Am I missing something or are you supposed to be able to run this exactly like the original one made by bbolli? I have both 2.7 and 3.9 for python and I can run the original just fine but when I try and run this version all I get is this long mess in command prompt with empty folders. It creates the folder for the blog, and then a blank folder for both media and posts.

Any help would be appreciated. I created the video for the original script and have had people coming to me for a while trying to solve some of these kinds of errors.

[Error When Running.txt](https://github.com/Cebtenzzre/tumblr-utils/files/5826733/Error.When.Running.txt)

**Comment by Cebtenzzre** [comment]
Thanks for the bug report! It looks like I need to test this script on Windows occasionally. I forgot that you can't `os.open` a directory on all platforms. Fix coming soon.

**Comment by Sheepykin** [comment]
Thanks! Yeah I am in the process of trying to help someone and with python2 being discontinued I am looking to help out in python3. Hope it is a simple on your end!

**Comment by Cebtenzzre** [comment]
@Sheepykin I ran the script on Windows and fixed a few issues based on what I found. Let me know if there is anything I missed.
